// Annual contract value (USD) per deal, keyed by deal name. Generated by `npm run sync-amounts` from the HubSpot deal amount field — edit in HubSpot, not here.
// Mirrors ../../data/deal-amounts.json — the Vercel deployment's root is
// dashboard/, so it can't read the repo-root JSON at runtime.
export const AMOUNTS = {
  "Ashgrove University": 100000,
  "Bluepine Retail": 80000,
  "Cascade Logistics": 150000,
  "Cedarhill Robotics": 60000,
  "Cobalt Ridge Energy": 100000,
  "Corvid Manufacturing": 60000,
  "Harbor Health Systems": 40000,
  "Ironvale Manufacturing": 75000,
  "Lakeshore Fintech": 65000,
  "Larkfield Hotels": 65000,
  "NovaWorks": 120000,
  "Ridgeline Telecom": 45000,
  "Trellis Logistics": 70000,
  "Varis Bancorp": 50000,
};
