// Pull deal amounts from HubSpot into the forecast's amount map.
//
//   npm run sync-amounts
//
// The risk-adjusted forecast needs a dollar value per deal. Those values live in
// HubSpot (the CRM is the system of record for money), but the dashboard deploys
// from dashboard/ on Vercel and can't read the repo-root JSON at runtime — hence
// two generated files, both written here:
//
//   data/deal-amounts.json    — used by `npm run forecast` and the Slack digest
//   dashboard/lib/amounts.js  — used by the deployed dashboard
//
// Amounts are keyed by the *Supabase* deal name, since that's what both consumers
// look up. A deal with no HubSpot match keeps whatever value it already had, so a
// deal that hasn't been pushed to the CRM yet doesn't silently drop out of the
// forecast totals.
import 'dotenv/config';
import { writeFile, readFile } from 'node:fs/promises';
import path from 'node:path';
import { supabase } from './db.js';

const JSON_FILE = path.resolve(process.cwd(), 'data', 'deal-amounts.json');
const JS_FILE = path.resolve(process.cwd(), 'dashboard', 'lib', 'amounts.js');
const COMMENT =
  'Annual contract value (USD) per deal, keyed by deal name. Generated by `npm run sync-amounts` from the HubSpot deal amount field — edit in HubSpot, not here.';

const TOKEN = process.env.HUBSPOT_TOKEN;
if (!TOKEN || TOKEN.includes('REPLACE_ME')) {
  console.error('HUBSPOT_TOKEN is not set — nothing to sync.');
  process.exit(1);
}

/** Every deal in the portal with its amount. Pages through the full list. */
async function fetchHubspotAmounts() {
  const out = [];
  let after;
  do {
    const qs = new URLSearchParams({ limit: '100', properties: 'dealname,amount' });
    if (after) qs.set('after', after);
    const res = await fetch(`https://api.hubapi.com/crm/v3/objects/deals?${qs}`, {
      headers: { Authorization: `Bearer ${TOKEN}` },
    });
    if (!res.ok) throw new Error(`HubSpot ${res.status}: ${await res.text()}`);
    const body = await res.json();
    out.push(...(body.results || []));
    after = body.paging?.next?.after;
  } while (after);
  return out;
}

const [{ data: deals, error }, hsDeals] = await Promise.all([
  supabase.from('deals').select('name').order('name'),
  fetchHubspotAmounts(),
]);
if (error) throw error;

// Index HubSpot by lowercased name so "NovaWorks" matches "novaworks".
const byName = new Map();
for (const d of hsDeals) {
  const n = d.properties?.dealname;
  const amt = d.properties?.amount;
  if (n && amt != null && amt !== '') byName.set(n.trim().toLowerCase(), Math.round(Number(amt)));
}

// Existing values, so an unmatched deal keeps its amount rather than dropping out.
let previous = {};
try {
  const raw = JSON.parse(await readFile(JSON_FILE, 'utf8'));
  previous = Object.fromEntries(Object.entries(raw).filter(([k]) => !k.startsWith('_')));
} catch {
  /* first run — no prior file */
}

const amounts = {};
const matched = [];
const kept = [];
const missing = [];
for (const { name } of deals) {
  const hit = byName.get(name.trim().toLowerCase());
  if (hit != null) {
    amounts[name] = hit;
    matched.push(`${name} → $${hit.toLocaleString('en-US')}`);
  } else if (previous[name] != null) {
    amounts[name] = previous[name];
    kept.push(`${name} → $${previous[name].toLocaleString('en-US')} (no HubSpot match, kept previous)`);
  } else {
    missing.push(name);
  }
}

await writeFile(JSON_FILE, JSON.stringify({ _comment: COMMENT, ...amounts }, null, 2) + '\n', 'utf8');

const body = Object.entries(amounts)
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${v},`)
  .join('\n');
await writeFile(
  JS_FILE,
  `// ${COMMENT}\n// Mirrors ../../data/deal-amounts.json — the Vercel deployment's root is\n` +
    `// dashboard/, so it can't read the repo-root JSON at runtime.\nexport const AMOUNTS = {\n${body}\n};\n`,
  'utf8'
);

console.log(`✓ synced ${matched.length} amount(s) from HubSpot`);
matched.forEach((m) => console.log(`   ${m}`));
if (kept.length) {
  console.log(`\n• kept ${kept.length} previous value(s):`);
  kept.forEach((m) => console.log(`   ${m}`));
}
if (missing.length) {
  console.log(`\n⚠ no amount anywhere (excluded from $ totals): ${missing.join(', ')}`);
}
console.log(`\nWrote data/deal-amounts.json and dashboard/lib/amounts.js.`);
console.log('Commit and push for the deployed dashboard to pick these up.');
